### ISSUE TITLE
users should be able resize sidebars and panels

### ISSUE THREAD

**Issue by DanielFGray** [DanielFGray/postgres-playground#12]
* https://github.com/bvaughn/react-resizable-panels

**Comment by aspizu** [comment]
What about drag-and-drop panels which can be placed in any layout the user desires, just like vscode?

**Comment by DanielFGray** [comment]
> What about drag-and-drop panels which can be placed in any layout the user desires, just like vscode?

there's a [https://github.com/DanielFGray/postgres-playground/tree/vscode](vscode branch) exploring this idea

**Comment by DanielFGray** [comment]
closed by 15b6a4649558cb940d36c2ff1004794ebddc839d
